model: Qwen/Qwen3-4B-Thinking-2507

use_local: true

load_dataset: true

sampling:
  temperature: 0.4
  top_p: 0.9
  presence_penalty: 0

datasets:
  - msmarco-passage/trec-dl-2019
  - beir/webis-touche2020
  - trec-fair/2021/train
